version: "3"
services:
  redis:
    image: redis:4.0
    container_name: redis4.0
    ports:
      - 6379:6379
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    volumes:
      - ~/docker/data/mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    hostname: nacos
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      PREFER_HOST_MODE: mysql
      SPRING_DATASOURCE_PLATFORM: mysql
      MODE: standalone
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      NACOS_APPLICATION_PORT: 8848
      JVM_XMS: 512m
      JVM_XMX: 512m
    volumes:
      - ~/docker/logs/nacos/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
  seata:
    image: seataio/seata-server:1.3.0
    hostname: seata
    container_name: seata
    depends_on:
      - nacos
      - mysql
    links:
      - nacos:nacos
      - mysql:mysql
    ports:
      - "8091:8091"
    environment:
      SEATA_PORT: 8091
      SEATA_IP: 10.44.1.133
    volumes:
      - ../../doc/seata/conf/registry.conf:/seata-server/resources/registry.conf
      - ../../doc/seata/conf/file.conf:/seata-server/resources/file.conf
      - ~/docker/logs/seata/:/root/logs/seata