version: '3'

services:
  sentinel-dashboard:
    image: sentinel:latest
    container_name: sentinel-dashboard
    environment:
      PASSWORD: 123456
    volumes:
      - ~/docker/logs/sentinel:/opt/logs
    ports:
      - 8801:8080
    restart: on-failure
